"""initial

Revision ID: 22e59fd43849
Revises:
Create Date: 2026-03-11 16:54:32.360126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22e59fd43849'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=150), nullable=False),
                    sa.Column('slug', sa.String(length=150), nullable=False),
                    sa.Column('region', sa.String(
                        length=100), nullable=True),
                    sa.Column('category', sa.String(
                        length=100), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('short_description', sa.String(
                        length=300), nullable=True),
                    sa.Column('highlights', postgresql.ARRAY(
                        sa.Text()), nullable=True),
                    sa.Column('best_season', sa.String(
                        length=100), nullable=True),
                    sa.Column('best_months', postgresql.ARRAY(
                        sa.Integer()), nullable=True),
                    sa.Column('difficulty', sa.String(
                        length=50), nullable=True),
                    sa.Column('min_days', sa.Integer(), nullable=True),
                    sa.Column('max_days', sa.Integer(), nullable=True),
                    sa.Column('base_price_per_day',
                              sa.Integer(), nullable=True),
                    sa.Column('image_url', sa.Text(), nullable=True),
                    sa.Column('rating', sa.Float(), nullable=False),
                    sa.Column('review_count', sa.Integer(), nullable=False),
                    sa.Column('latitude', sa.Float(), nullable=True),
                    sa.Column('longitude', sa.Float(), nullable=True),
                    sa.Column('tags', postgresql.ARRAY(
                        sa.Text()), nullable=True),
                    sa.Column('is_featured', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('slug')
                    )
    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('full_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('username', sa.String(
                        length=50), nullable=False),
                    sa.Column('email', sa.String(length=150), nullable=False),
                    sa.Column('password_hash', sa.Text(), nullable=False),
                    sa.Column('travel_style', sa.String(
                        length=50), nullable=True),
                    sa.Column('preferred_difficulty', sa.String(
                        length=50), nullable=True),
                    sa.Column('preferred_budget_tier', sa.String(
                        length=50), nullable=True),
                    sa.Column('cluster_id', sa.Integer(), nullable=True),
                    sa.Column('cluster_label', sa.String(
                        length=100), nullable=True),
                    sa.Column('adventure_score', sa.Float(), nullable=False),
                    sa.Column('cultural_score', sa.Float(), nullable=False),
                    sa.Column('nature_score', sa.Float(), nullable=False),
                    sa.Column('luxury_score', sa.Float(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('activities',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('destination_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=150), nullable=True),
                    sa.Column('category', sa.String(
                        length=100), nullable=True),
                    sa.Column('duration_hours', sa.Float(), nullable=True),
                    sa.Column('difficulty', sa.String(
                        length=50), nullable=True),
                    sa.Column('price_npr', sa.Integer(), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('available_months', postgresql.ARRAY(
                        sa.Integer()), nullable=True),
                    sa.ForeignKeyConstraint(['destination_id'], [
                        'destinations.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('hotels',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('destination_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=150), nullable=True),
                    sa.Column('tier', sa.String(length=50), nullable=True),
                    sa.Column('price_per_night', sa.Integer(), nullable=True),
                    sa.Column('rating', sa.Float(), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('amenities', postgresql.ARRAY(
                        sa.Text()), nullable=True),
                    sa.ForeignKeyConstraint(['destination_id'], [
                        'destinations.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('itineraries',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('destination_id', sa.UUID(), nullable=True),
                    sa.Column('destination_name', sa.String(
                        length=150), nullable=True),
                    sa.Column('region', sa.String(length=100), nullable=True),
                    sa.Column('num_days', sa.Integer(), nullable=True),
                    sa.Column('travel_month', sa.String(
                        length=20), nullable=True),
                    sa.Column('budget_tier', sa.String(
                        length=50), nullable=True),
                    sa.Column('hotel_type', sa.String(
                        length=50), nullable=True),
                    sa.Column('interests', sa.Text(), nullable=True),
                    sa.Column('difficulty', sa.String(
                        length=50), nullable=True),
                    sa.Column('predicted_budget', sa.Integer(), nullable=True),
                    sa.Column('actual_schedule', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['destination_id'], ['destinations.id'], ),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('reviews',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('destination_id', sa.UUID(), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=False),
                    sa.Column('comment', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.CheckConstraint('rating >= 1 AND rating <= 5',
                                      name='ck_rating_range'),
                    sa.ForeignKeyConstraint(['destination_id'],
                                            ['destinations.id'],
                                            ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'destination_id',
                                        name='uq_user_destination_review')
                    )
    op.create_table('saved_places',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('destination_id', sa.UUID(), nullable=False),
                    sa.Column('saved_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['destination_id'], [
                        'destinations.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'destination_id',
                                        name='uq_user_destination_saved')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_places')
    op.drop_table('reviews')
    op.drop_table('itineraries')
    op.drop_table('hotels')
    op.drop_table('activities')
    op.drop_table('users')
    op.drop_table('destinations')
    # ### end Alembic commands ###
